CREATE TABLE IF NOT EXISTS DB (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL
);
TRUNCATE TABLE DB;
INSERT INTO DB (name) VALUES ('taco');
INSERT INTO Db (name) VALUES ('tacobell');
